version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: aspire.zookeeper.blog
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:latest
    container_name: aspire.kafka.blog
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: 'topic-jhipster:1:1'
      #KAFKA_MESSAGE_MAX_BYTES: 10000000
      #KAFKA_REPLICA_FETCH_MAX_BYTES: 10000000
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: 60000
      KAFKA_NUM_PARTITIONS: 2
    ports:
      - 9092:9092
  kafka-manager:
    image: sheepkiller/kafka-manager:latest
    container_name: aspire.kafka.manager.blog
    ports:
      - 9094:9000
    links:
      - zookeeper
      - kafka
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true

